
// API 1
// get all the player details from the data base 
GET http://localhost:3000/players/
###
// API 2
// post the new player into data base. 
//Player is auto incremented
// create a new player by chnaging the details below and run
POST http://localhost:3000/players/
Content-Type: application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 17,
  "role": "Bowler"
}

###
// get player details based on player ID 
// change the player ID(i.e 14 in example ) to check for remaining players 
// API 3
GET http://localhost:3000/players/14/


###
// update the player details based on player ID given 
//API 4
PUT http://localhost:3000/players/14/
Content-Type: application/json

{
"playerName": "Maneesh",
  "jerseyNumber": 54,
  "role": "All-rounder"
}

### 
// Delete the player details by the given player Id 
// API 5 
DELETE http://localhost:3000/players/12/